version: '3.4'

services:
  node:
    image: node:lts-alpine
    container_name: phaser2_node
    user: node
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 3000:3000
    command: "npm run dev"
