version: "3.4"
name: phaser_base

services:
  node:
    image: node:18-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-node
    user: node
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      NPM_CONFIG_engine-strict: true
    ports:
      - 3000:3000
      - 9229:9229
    command: >
      sh -c "npm ci &&
             npm run dev"
  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    ports:
      - 6379:6379
    restart: unless-stopped
    #volumes:
    # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # - ./redis/redis-data:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ${COMPOSE_PROJECT_NAME}-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: ${COMPOSE_PROJECT_NAME}-mkdocs
    ports:
      - 8000-8010:8000
    volumes:
      - type: bind
        source: ./docs
        target: /docs/docs
      - type: bind
        source: ./docs/mkdocs.yml
        target: /docs/mkdocs.yml
