version: '3.4'
name: phaser_base

services:
  node:
    image: node:18-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-node
    user: node
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: "npm run dev"
  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    ports:
      - 6379:6379
    restart: unless-stopped
    #volumes:
    # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # - ./redis/redis-data:/data
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: ${COMPOSE_PROJECT_NAME}-mkdocs
    ports:
      - 8000-8010:8000
    volumes:
      - type: bind
        source: .
        target: /docs
